#!/bin/bash
set -euo pipefail

# GPU PCIe address
GPU="01:00.0"

fail() {
    echo "$1" >&2
    exit 1
}

info() {
    echo "$1"
}

safe_modprobe() {
    local output
    if ! output=$(modprobe "$@" 2>&1); then
        if echo "$output" | grep -q "Module amdgpu is in use"; then
            return 0
        else
            fail "$output"
        fi
    fi
}

if [[ "$EUID" -ne 0 ]]; then
    fail "root permissions are required"
fi

UID_USER=$(id -u "${SUDO_USER:-1000}" 2>/dev/null || echo 1000)
driver=$(lspci -nnk -s "$GPU" | awk -F': ' '/Kernel driver in use/ {print $2}')

[[ -z "${driver:-}" ]] && fail "Could not find driver in use for $GPU"

if [[ "$driver" == "vfio-pci" ]]; then
    info "vfio-pci is already loaded"
    exit 0
fi

systemctl stop nvidia-persistenced
nvidia-smi -pm 0

if fuser /dev/nvidia* >/dev/null 2>&1; then
    sudo -u "#$UID_USER" DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$UID_USER/bus" notify-send -i dialog-error -t 3000 "GPU Driver" "NVIDIA GPU is in use, cannot switch driver"
    fail "NVIDIA GPU is in use, can not switch driver, check failed on /dev/nvidia*"
fi

NVIDIA_CARD="/dev/dri/by-path/pci-0000:$GPU-card"
NVIDIA_RENDER="/dev/dri/by-path/pci-0000:$GPU-render"

if fuser "$NVIDIA_CARD" "$NVIDIA_RENDER" >/dev/null 2>&1; then
    sudo -u "#$UID_USER" DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$UID_USER/bus" notify-send -i dialog-error -t 3000 "GPU Driver" "NVIDIA GPU is in use, cannot switch driver"
    fail "NVIDIA GPU is in use, can not switch driver, check faield on /dev/dri"
fi

safe_modprobe -r nvidia_uvm || fail "Could not unload nvidia_uvm"
safe_modprobe -r nvidia_drm || fail "Could not unload nvidia_drm"
safe_modprobe -r nvidia_modeset || fail "Could not unload nvidia_modeset"
safe_modprobe -r nvidia || fail "Could not unload nvidia_modeset"
safe_modprobe -r i2c_nvidia_gpu || fail "Could not unload i2c_nvidia_gpu"

safe_modprobe vfio || fail "Could not load vfio"
safe_modprobe vfio_pci || fail "Could not load vfio_iommu_type1"
safe_modprobe vfio_iommu_type1 || fail "Could not load vfio_pci"

gpu-check
info "Loaded vfio-pci driver successfuly"
sudo -u "#$UID_USER" DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$UID_USER/bus" notify-send -i emblem-success -t 3000 "GPU Driver" "Switched GPU driver to VFIO"
exit 0
